version: '3.8'

services:
  db:
    build:
      context: ./src/database
      dockerfile: Dockerfile
    image: opencourt-db:local
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./src/database/create_tables.sql:/docker-entrypoint-initdb.d/01-create_tables.sql
      - ./src/database/seed_tables.sql:/docker-entrypoint-initdb.d/02-seed_tables.sql

  backend:
    build:
      context: ./src/server
      dockerfile: Dockerfile
    image: opencourt-backend:local
    restart: always
    environment:
      PORT: 3000
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: 3306
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./src/server:/usr/src/app
      - /usr/src/app/node_modules

  frontend:
    build:
      context: ./src/frontend/opencourt
      dockerfile: Dockerfile
      args:
        - VITE_SERVER_HOST=backend
        - VITE_SERVER_PORT=3000
        - VITE_SERVER_BASE_URL=
    image: opencourt-frontend:local
    restart: always
    environment:
      # Not strictly required at runtime because the built assets have the API host baked in
      VITE_SERVER_HOST: backend
      VITE_SERVER_PORT: 3000
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mysql-data: